#libs-y += -lpxa
obj-$(CONFIG_IGUANA) += generic.o
obj-$(CONFIG_CELL) += generic.o time.o clock.o dma.o

#obj-$(CONFIG_PXA27x) += pxa27x.o
obj-$(CONFIG_PXA25x) += pxa25x.o

#obj-$(CONFIG_IBOX) += ibox.o
#obj-$(CONFIG_PLEB2) += pleb2.o
#obj-$(CONFIG_ARCH_GUMSTIX) += gumstix.o
