Import("*")

libs = ["l4", "l4e", "mutex", "atomic_ops", "c", "okl4", "driver"]

try:
    if args["serial_driver"]:
        libs.append(args["serial_driver"])
        libs.append("serial")
        env.Append(CPPDEFINES=[("SERIAL_DRIVER", args["serial_driver"])])
except:
    pass

# Add kernel-specific libraries
if env.kernel == "micro":
    libs += ["l4", "mutex"]
elif env.kernel == "nano":
    libs += ["nano"]
else:
    raise UserError, "Unknown kernel"

obj = env.KengeProgram("echo", LIBS=libs)

env.expect_test_data = [("Drivers works!", None)]

env.set_program(obj, heap = 0x100000)

Return("obj")
