obj-$(CONFIG_IG_RAMDISK) := ig_ramdisk.o
obj-$(CONFIG_FB_IGVIRTUAL)  += ig_fb.o cfbcopyarea.o cfbfillrect.o cfbimgblt.o
obj-$(CONFIG_L4KDB_CONSOLE) += l4kdb_console.o
obj-$(CONFIG_IG_SERIAL) += ig_serial.o
obj-$(CONFIG_IG_INPUT) += ig_input.o

obj-$(CONFIG_IG_NET) += ig_net.o
obj-$(CONFIG_IG_MMC) += ig_mmc.o
obj-$(CONFIG_MTD_IGMTD) += ig_mtd.o
obj-$(CONFIG_IG_AUDIO) += ig_audio.o
obj-$(CONFIG_IG_TOUCH) += ig_touch.o
obj-$(CONFIG_DECRYPT) += cross_cell_demo.o
