Import("*")
import os
build_dir = Dir(env.builddir + "/ncurses").abspath
inst_dir = Dir(env.builddir + "/install").abspath
root_dir = Dir("#").abspath
ncurses_dir = "ncurses"


def b(file_name):
   return os.path.join(build_dir, file_name)
def i(file_name):
   return os.path.join(inst_dir, file_name)

env.scons_env["MAKE"] = "make"


ncurses_conf = env.Command(b("Makefile"),
                         [],
			  "cd %s && DESTDIR=%s %s/linux/apps/%s/configure --host=arm-linux  --prefix=/usr --enable-termcap" % (build_dir, inst_dir, root_dir, ncurses_dir)
			  )

ncurses = env.Command(b("ncurses.built"),
                     ncurses_conf,
                     "cd %s && $MAKE -j %d && touch ncurses.built" %
		     (build_dir, GetOption('num_jobs')))
		     
ncurses_install = env.Command(i("usr/lib/ncurses.a"),
                            ncurses,
			     "cd %s && $MAKE install.libs install.data" % build_dir
			     )

env.Depends(ncurses, ncurses_conf)
env.Depends(ncurses_install, ncurses)

Return("ncurses_install")
