import os.path
import glob
Import("*")

build_dir = Dir(env.builddir + "/lmbench").abspath
inst_dir = Dir(env.builddir + "/linux/install").abspath

liblmbench = env.StaticLibrary("lmbench", src_glob("src/lib_*.c") + ["src/getopt.c"],
                            CPPPATH="include", CCFLAGS=[], CC_WARNINGS=[])[0]

tests = []

paths = src_glob("src")
excepts = ["Makefile"]
paths = [path for path in paths if
         os.path.basename(path) not in excepts]

for path in paths:
    tests += src_glob("%s/*.c" % path)

excludes = ["lib_", "clock", "lat_pmake", "getopt", "seek", "flushdisk"]

def listStartsWith(item, list):
    for each in list:
	if item.startswith(each):
	    return 1
    return 0

tests = [each for each in tests if not listStartsWith(str(each).split(os.sep)[-1], excludes) ]

files = []
bindir = "%s/lmbench/bin/wombat" % inst_dir
scriptdir = "%s/lmbench/scripts" % inst_dir

for test in tests:
    CPPDEFINES = []
    files += Install(bindir,
                     env.Program(test,
                                 CPPPATH=["src"],
                                 LIBS=["lmbench", "m"],
                                 CPPDEFINES = CPPDEFINES,
                                 CCFLAGS=[],
                                 CC_WARNINGS=[],
                                 _LINKADDRESS="",
                                 _LINK="gcc",
                                 LINKFLAGS=[],
                                 LIBPATH=[os.path.dirname(liblmbench.abspath)])
                     )

src_flushdisk = []
src_flushdisk.append(("flushdisk", ["src/flushdisk.c"]))

for name, src in src_flushdisk:
    files += Install(bindir,
                     env.Program(name, src,
                                 CPPDEFINES = ["MAIN"],
                                 CCFLAGS=[],
                                 CC_WARNINGS=[],
                                 _LINKADDRESS="",
                                 _LINK="gcc",
                                 LINKFLAGS=[])
                     )

files += Install(scriptdir, "scripts/lmbench")
files += Install(scriptdir, "scripts/os")
files += Install(scriptdir, "scripts/config")
files += Install(scriptdir, "scripts/config-run")
files += Install(scriptdir, "scripts/version")
files += Install(scriptdir, "scripts/info")
files += Install(scriptdir, "scripts/results")
files += Install(scriptdir, "scripts/getpercent")
files += Install(scriptdir, "scripts/hello")
files += Install(scriptdir, "scripts/run_all_lmbench")
files += Install(scriptdir, "scripts/lmbench_part_init")
files += Install(scriptdir, "scripts/lmbench_part_1_latency")
files += Install(scriptdir, "scripts/lmbench_part_2_localnet")
files += Install(scriptdir, "scripts/lmbench_part_3_bwidth")
files += Install(scriptdir, "scripts/lmbench_part_4_ctx")
files += Install(scriptdir, "scripts/lmbench_part_5_tlb_memload")
files += Install(scriptdir, "scripts/lmbench_xml")
files += Install(scriptdir, "scripts/lmbench_xml_init")
files += Install(scriptdir, "scripts/run_lmbench_from_init")
files += Install(scriptdir, "scripts/CONFIG.wombat")


Return("files")
