#!/bin/sh

. $TESTS_DIR/lib/testlib

run_oklinux_test_quiet "Reading from /dev/fb0... " \
    "dd if=/dev/fb0 of=/tmp/fbdata bs=1024 count=16"
run_oklinux_test_quiet "Writing to /dev/fb0... " \
    "dd if=/tmp/fbdata.okl of=/dev/fb0 bs=1024 count=512"

rm /tmp/fbdata
rm /tmp/fbdata.okl
