Import("env", "args")
import os

# Get SRC directory
src_root = Dir('#').srcnode().abspath

# Check architecture exists
arch = env.machine.arch
arch_path = os.path.join('arch', arch, args['package'])

possible_arch_path = os.path.join("cust", args["cust"], "arch", arch, args["package"])
if os.path.exists(os.path.join(src_root, possible_arch_path)):
    arch_path = possible_arch_path

if not os.path.exists(os.path.join(src_root, arch_path)):
    print "architecture %s is not yet supported by libokl4." % (arch)

arch_path = "#" + arch_path

source = [ arch_path + "/src/*.c", arch_path + "/src/*.spp" ]

# Setup the library
lib = env.KengeLibrary("okl4", \
        FLINT_OPTIONS=[File("libokl4.lnt")], \
        extra_source=source)

Return("lib")

